import asyncio
import sqlite3
import os
from langchain_google_genai import ChatGoogleGenerativeAI
from pydantic import BaseModel

# Database Setup
DB_PATH = "/home/chris/wordhord/wordhord.db"

def load_google_api_key() -> str:
    key = os.getenv("GOOGLE_API_KEY")
    if key:
        return key
    try:
        api_key_file = os.getenv("API_KEY_FILE", "/home/chris/wordhord/wordhord_api.txt")
        with open(api_key_file, "r") as f:
            return f.read().strip()
    except FileNotFoundError:
        return None

GOOGLE_API_KEY = load_google_api_key()
if not GOOGLE_API_KEY:
    print("No GOOGLE_API_KEY found. Check /home/chris/wordhord/wordhord_api.txt")
    exit(1)

llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", google_api_key=GOOGLE_API_KEY, temperature=0)

async def clean_term(language, term, pos):
    prompt = f"""
Language: {language}
Original term: "{term}"
Part of speech: {pos}

The term above was generated by an AI and contains errors like:
- Leading articles (e.g. "En", "Ett", "Den", "Det", "Der", "Die", "Das")
- AI junk like brackets or numbers (e.g. "En] anledning", "Bara 2")
- Embedded parts of speech (e.g. "Aldrig adverb", "Adj. akademisch")
- Mixed languages (e.g. German words in Swedish cards)

TASK: Provide ONLY the clean, base word or phrase in {language}. 
- For Swedish: NO leading articles.
- For German nouns: Include the correct article (Der, Die, Das) ONLY if it's a noun.
- Remove all brackets, numbers, POS markers, and junk.
- Return ONLY the word/phrase, nothing else.

Cleaned term:"""
    
    try:
        response = await llm.ainvoke(prompt)
        cleaned = response.content.strip().strip('"').strip("'")
        # Basic sanity check: if the LLM returned something very long or empty, fallback
        if len(cleaned) > 50 or not cleaned:
            return term
        return cleaned
    except Exception as e:
        print(f"LLM Error for {term}: {e}")
        return term

async def main():
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    # Target cards that look messy
    cursor.execute("""
        SELECT id, language, term, part_of_speech 
        FROM cards 
        WHERE language IN ('swedish', 'german') 
        AND (
            term LIKE '%]%' OR 
            term LIKE '%(%' OR 
            term LIKE '% %' OR 
            term LIKE '%.%' OR 
            term LIKE '%/%' OR
            term LIKE '%adv%' OR
            term LIKE '%adj%' OR
            term LIKE '%noun%'
        )
    """)
    rows = cursor.fetchall()
    print(f"Found {len(rows)} potentially messy cards.")
    
    # Process in batches to avoid rate limits or overwhelming
    batch_size = 20
    for i in range(0, len(rows), batch_size):
        batch = rows[i:i+batch_size]
        tasks = []
        for card_id, lang, term, pos in batch:
            tasks.append(clean_term(lang, term, pos))
        
        cleaned_terms = await asyncio.gather(*tasks)
        
        for (card_id, lang, original_term, pos), cleaned_term in zip(batch, cleaned_terms):
            if cleaned_term != original_term:
                # Capitalize first letter (standard practice for this app)
                if cleaned_term:
                    cleaned_term = cleaned_term[0].upper() + cleaned_term[1:]
                
                # Check for collisions
                cursor.execute("SELECT id FROM cards WHERE language = ? AND term = ? AND id != ?", (lang, cleaned_term, card_id))
                collision = cursor.fetchone()
                
                if collision:
                    # Merge progress if needed (optional but good)
                    cursor.execute("DELETE FROM cards WHERE id = ?", (card_id,))
                    print(f"Merged: '{original_term}' -> '{cleaned_term}'")
                else:
                    try:
                        cursor.execute("UPDATE cards SET term = ? WHERE id = ?", (cleaned_term, card_id))
                        print(f"Fixed: '{original_term}' -> '{cleaned_term}'")
                    except sqlite3.IntegrityError:
                        cursor.execute("DELETE FROM cards WHERE id = ?", (card_id,))
                        print(f"Merged (IntegrityError): '{original_term}' -> '{cleaned_term}'")
        
        conn.commit()
        print(f"Processed {i + len(batch)} / {len(rows)}")
        await asyncio.sleep(0.5) # Short sleep to be nice to API

    conn.close()
    print("All messy cards processed.")

if __name__ == "__main__":
    asyncio.run(main())
